// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestPayTech.Database;

#nullable disable

namespace TestPayTech.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TestPayTech.Database.Entities.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModificationWebhook")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdDossier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodePaiement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomProduitPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatutPaiement")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelephoneClient")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier")
                        .IsUnique();

                    b.ToTable("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
